#+TITLE: Helm-SLIME

Helm for [[https://github.com/slime/slime][SLIME]], the Superior Lisp Interaction Mode for Emacs, and its cousin [[https://github.com/joaotavora/sly  joaotavora/sly][Sly]].

* Installation

Add =helm-slime.el= to your load-path.
Set up SLIME or Sly properly.

If you use SLIME, call ~slime-setup~ and include ~'helm-slime~ as the arguments:

#+begin_src lisp
(slime-setup '([others contribs ...] helm-slime))
#+end_src

or simply require ~helm-slime~ in some appropriate manner.

To use Helm instead of the Xref buffer, enable ~global-helm-slime-mode~.

To enable Helm for completion, install [[https://github.com/Sodel-the-Vociferous/helm-company][helm-company]].  With SLIME, you'll
also need [[https://github.com/anwyn/slime-company/][slime-company]].  Then:

- SLIME:
  #+begin_src lisp
  (slime-setup '(slime-company))
  (require 'helm-company)
  (define-key slime-repl-mode-map (kbd "<tab>") 'helm-company)
  #+end_src

- Sly:
  #+begin_src lisp
  (add-hook 'sly-mrepl-hook #'company-mode)
  (require 'helm-company)
  (define-key sly-mrepl-mode-map (kbd "<tab>") 'helm-company)
  #+end_src

* Usage

Helm-SLIME defines a few new commands:

- helm-lisp-list-connections :: Yet another Lisp connection list with `helm'.

- helm-lisp-apropos :: Yet another ~apropos~ with Helm.

- helm-lisp-repl-history :: Select an input from the REPL history and insert it.

- helm-lisp-mini :: Like ~helm-lisp-list-connections~, but include an extra
                    source of Lisp-related buffers, like the events buffer or
                    the scratch buffer.

* Changelog

** 0.5

- Add support for Sly.
- Move from the =helm-slime= prefix to the =helm-lisp= prefix.
- Remove the =helm-slime-complete= function in favour of =helm-company=.
